name: Build SARS-COVID images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-aln2type-docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: aln2type
          tags: oxfordmmm/aln2type:latest, oxfordmmm/aln2type:${{env.RELEASE_VERSION}}
          push: true
      -
        name: Docker digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-aln2type-sing:
    runs-on: self-hosted
    needs: build-aln2type-docker
    strategy:
      matrix:
        singularity_version:
          - '3.5.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: build singularity
        run: singularity build aln2type_${{env.RELEASE_VERSION}}.sif docker://oxfordmmm/aln2type:${{env.RELEASE_VERSION}}

  build-nextclade-sing:
    runs-on: self-hosted
    strategy:
      matrix:
        singularity_version:
          - '3.5.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: build singularity
        run: singularity build nextclade_${{env.RELEASE_VERSION}}.sif docker://neherlab/nextclade:latest
  
  build-oci-docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: OCI_object_HRR
          tags: oxfordmmm/oci_pipeline:latest, oxfordmmm/oci_pipeline:${{env.RELEASE_VERSION}}
          push: true
      -
        name: Docker digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-oci-sing:
    runs-on: self-hosted
    needs: build-oci-docker
    strategy:
      matrix:
        singularity_version:
          - '3.5.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: build singularity
        run: singularity build oci_pipeline_${{env.RELEASE_VERSION}}.sif docker://oxfordmmm/oci_pipeline:${{env.RELEASE_VERSION}}
  
  build-pango-docker:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: pango
          tags: oxfordmmm/pango:latest, oxfordmmm/pango:${{env.RELEASE_VERSION}}
          push: true
      -
        name: Docker digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-pango-sing:
    runs-on: self-hosted
    needs: build-pango-docker
    strategy:
      matrix:
        singularity_version:
          - '3.5.3'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - 
        name: build singularity
        run: singularity build pango_${{env.RELEASE_VERSION}}.sif docker://oxfordmmm/pango:${{env.RELEASE_VERSION}}