name: Automatically build every Sunday

on:
  schedule:
    - cron: '50 13 * * 0'

jobs:
  create_new_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Define new version'
        run: |
          CURRENT_VERSION=$(git tag -l --sort=-version:refname | head -n 1)
          echo "Current Version = $CURRENT_VERSION"
          readarray -d . -t strarr <<< "$CURRENT_VERSION"
          ((strarr[-1]+=1))
          NEW_VERSION="${strarr[0]}"
          for elem in "${strarr[@]:1}";do NEW_VERSION="$NEW_VERSION.$elem"; done
          echo "New Version = $NEW_VERSION"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}